GET http://localhost:3001/api/supervisorBoard
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YTRmOGM0ZWFiZTUyMWQ2Yzg5NTZjYiIsImlhdCI6MTcyMjA4NzkwMCwiZXhwIjoxNzIyMTc0MzAwfQ.1lVkpBr_bv_juJt1KzCtgesEexuv34X0GSD30TJGAu0


###

POST http://localhost:3001/api/signUp
Content-Type: application/json

{
  "email": "USEuser1@goo.com",
  "password": "asAdasa1das"
}

### 

POST http://localhost:3001/api/signIn
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "Password123"
}

###

PUT http://localhost:3001/api/addSupervisor
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YTRmZjAzM2EyZWRlNDZmMGFkNDNjZSIsImlhdCI6MTcyMjA4OTIzMiwiZXhwIjoxNzIyMTc1NjMyfQ.q8II8Sr8dsOwzAYEMVIwzRoRNDOm1NkDPhEH6Ah-Uw8
Content-Type: application/json

{
  "email": "user@example.com"
}